### ISSUE TITLE
autoload.php

### ISSUE THREAD

**Issue by RayzonDE** [Tustin/fortnite-php#14]
Where can I get the 'vendor/autoload.php' ?

**Comment by monkeydioude** [comment]
This is not a "asking" section, this section is made for **issues** relative to the **project** itself.

Also your answer is written right in the [README.md](https://github.com/Tustin/fortnite-php/blob/master/README.md). You could even try before asking...

**Comment by monkeydioude** [comment]
It is, that'd would mean you'd have to require manually every file needed.
Or you could just run a docker image of composer for building the dependencies, if you really don't wanna install composer (which is only a single light file to download tho)

**Comment by monkeydioude** [comment]
@RayzonDE don't thank people helping you...
