### ISSUE TITLE
Can't get leaderboards

### ISSUE THREAD

**Issue by Arthuravila** [Tustin/fortnite-php#19]
`Fatal error: Uncaught GuzzleHttp\Exception\ServerException: Server error: 'POST https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/leaderboards/type/global/stat/br_placetop1_pc_m0_p10/window/weekly?ownertype=1&itemsPerPage=50` resulted in a `500 Internal Server Error' response: {"errorCode":"errors.com.epicgames.common.server_error","errorMessage":"Sorry an error occurred and we were unable to re (truncated...) in C:\xampp\htdocs\fortnite\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113 Stack trace: #0 C:\xampp\htdocs\fortnite\vendor\guzzlehttp\guzzle\src\Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 C:\xampp\htdocs\fortnite\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 C:\xampp\htdocs\fortnite\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), in C:\xampp\htdocs\fortnite\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113`

**Comment by Tustin** [comment]
This is an error on Epic's end. Their API is returning a 500, which indicates something failed on their server. Try it again a bit later and it should work.

**Comment by KilianSmt** [comment]
Same on my side, I did not have the opportunity to see the time that took the request but already just to have the information of a player it takes a little time, for a ranking it must be long enough.
All sites currently use their own rankings I think, it's probably the best way.

**Comment by Tustin** [comment]
Just looked at it myself and yeah, it seems like either Epic changed something to break unofficial services or they broke something on the endpoint. I'm going to assume they did it intentionally and try to come up with some way to get around their certificate pinning so I can check it out.

**Comment by Arthuravila** [comment]
Hi, no idea about how to resolve this issue? ty

**Comment by Krokit** [comment]
![image](https://user-images.githubusercontent.com/8360887/43986584-b0ffd612-9d1b-11e8-9d34-48fbdad2d7a0.png)
After I try about 232323 times I finally manage to get leaderboards. After checking some things I will push RP

**Comment by NeVeR2TrY** [comment]
@Krokit how to pass the ids list to the api in code?

as i see "group" works to get leaderboards on specific list right ?

**Comment by Krokit** [comment]
Check what i change in the RP (#36)

**Comment by NeVeR2TrY** [comment]
@Krokit i know but you used group in the photo instead of global, while in the code global is used
groups filters using given ids right?
how to pass ids?

also have you checked how to get other leaderboards types? like kills etc...
