### ISSUE TITLE
Can't login, RuntimeException GuzzleHttp

### ISSUE THREAD

**Issue by Tusta** [Tustin/fortnite-php#21]
Fatal error: Uncaught exception 'RuntimeException' with message 'GuzzleHttp requires cURL, the allow_url_fopen ini setting, or a custom HTTP handler.' in /users/tusta/www/EpicRoyale/vendor/guzzlehttp/guzzle/src/functions.php:119 Stack trace: #0 /users/tusta/www/EpicRoyale/vendor/guzzlehttp/guzzle/src/HandlerStack.php(40): GuzzleHttp\choose_handler() #1 /users/tusta/www/EpicRoyale/vendor/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\HandlerStack::create() #2 /users/tusta/www/EpicRoyale/vendor/tustin/fortnite-php/src/FortniteClient.php(74): GuzzleHttp\Client->__construct() #3 /users/tusta/www/EpicRoyale/vendor/tustin/fortnite-php/src/Auth.php(55): Fortnite\FortniteClient::sendUnrealClientPostRequest('https://account...', Array) #4 /users/tusta/www/EpicRoyale/index.php(34): Fortnite\Auth::login('', '') #5 {main} thrown in /users/tusta/www/EpicRoyale/vendor/guzzlehttp/guzzle/src/functions.php on line 119

**Comment by Tustin** [comment]
Make sure cURL for PHP is installed on your server.

**Comment by Tusta** [comment]
Thanks now it works but I have a new problem.  

> Parse error: syntax error, unexpected ':', expecting ';' or '{' in /var/customers/webs/ni985346_1/vendor/tustin/fortnite-php/src/Stats.php on line 101

**Comment by Tustin** [comment]
You need the latest version of PHP (>=7.0) for this. If you pulled it in using composer it shouldn't gave an error or warning that you need to update PHP.

**Comment by Tusta** [comment]
Thank you!
