### ISSUE TITLE
400 Bad Request` response

### ISSUE THREAD

**Issue by elsuper-migueld** [Tustin/fortnite-php#22]
HI, there's an error. Pls can u help me.

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://account-public-service-prod03.ol.epicgames.com/account/api/oauth/token` resulted in a `400 Bad Request` response: { "errorCode" : "errors.com.epicgames.account.invalid_account_credentials", "errorMessage" : "Sorry the account cred (truncated...) in /Users/migueld/projects/php/fortnite_api/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /Users/migueld/projects/php/fortnite_api/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /Users/migueld/projects/php/fortnite_api/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /Users/migueld/projects/php/fortnite_api/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 /Users/migueld/proje in /Users/migueld/projects/php/fortnite_api/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

I also used your fortnitetracker app.
and I have this error
(1/1) ClientException
Client error: `POST https://account-public-service-prod03.ol.epicgames.com/account/api/oauth/token` resulted in a `400 Bad Request` response:
{
"errorCode" : "errors.com.epicgames.account.invalid_account_credentials",
"errorMessage" : "Sorry the account cred (truncated...)

**Comment by Tustin** [comment]
Well the obvious thing is to make sure you're using the right username/password, as that's what the error is (most likely) saying. If you know your info is correct, make sure you've played Fortnite on that account at least once.

**Comment by elsuper-migueld** [comment]
Hi, thanks for your fast reply.
Today I tried with 3 different accounts and the same problem

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://account-public-service-prod03.ol.epicgames.com/account/api/oauth/token` resulted in a `400 Bad Request` response: { "errorCode" : "errors.com.epicgames.account.invalid_account_credentials", "errorMessage" : "Sorry the account cred (truncated...) in /Users/migueld/projects/php/fortnite_api/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /Users/migueld/projects/php/fortnite_api/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /Users/migueld/projects/php/fortnite_api/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /Users/migueld/projects/php/fortnite_api/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 /Users/migueld/proje in /Users/migueld/projects/php/fortnite_api/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

I played at least one match with each one.
Do you have any idea, what the problem is?

pd. sorry my english isn't very good.

**Comment by KilianSmt** [comment]
Hey, do u accept the terms of use?
If u don't launch fortnite one time in ur account it is temporarily blocked until you accept them.

**Comment by elsuper-migueld** [comment]
Hi KillianSmt, yes I accepted the term of use.
I played 3 matches, I dont play fortnite very often, But I played with the account that I tried to use the api.

**Comment by elsuper-migueld** [comment]
everything works fine. Today I played like 7 matches. Then I tried again and works.
