### ISSUE TITLE
terminate all logged sessions.

### ISSUE THREAD

**Issue by SpectreMz** [Tustin/fortnite-php#26]
how i can terminate all sessions created with login function of AUTH class?

**Comment by Tustin** [comment]
You can use the `unset` PHP function to get rid of an existing variable. Other than that, it doesn't really matter if you have unused OAuth tokens from the Fortnite API. They'll just get refreshed when you log in again.

**Comment by Tustin** [comment]
Solved this with e0da9392f219773ff5a50de75a51b40cf7f2bf8e. Use the killSession() method inside the account class to kill the current access token.
