### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by dpather** [Tustin/fortnite-php#27]
Not Sure if the contribution message is related.

However, I am getting the following error when trying to run the test php file in cmd (Windows)

PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

Any ideas on how to resolve this issue in order to use this wrapper?

Thanks

**Comment by Tustin** [comment]
This is an issue where you don't have a valid SSL certificate for cURL to use. Try this solution and see if it fixes your problem: https://stackoverflow.com/a/34883260

**Comment by dpather** [comment]
Thank you worked!
