### ISSUE TITLE
K/D ratio cleanup!

### ISSUE THREAD

**Issue by Tusta** [Tustin/fortnite-php#29]
Hello Tustin, Here is a cleanup for the K/D ratio in 

> FortniteStats.php

`$this->kill_death_ratio = ($this->matches_played - $this->wins === 0) ? 0 : round(@($this->kills) / ($this->matches_played - $this->wins), 2);`

**Comment by Tustin** [comment]
Thanks, but if you could fork the repo and add this with a pull request, that would be better :).
