### ISSUE TITLE
Fatal error: Uncaught Error: Class 'GuzzleHttp\Client' not found

### ISSUE THREAD

**Issue by UnknowColum** [Tustin/fortnite-php#3]
Hello, i have little problem

erreur 
```
Fatal error: Uncaught Error: Class 'GuzzleHttp\Client' not found in /home/xxxxxx/api/xxxxxx/libs/Fortnite/FortniteClient.php:67 

Stack trace: #0 /home/xxxxxx/api/xxxxxx/libs/Fortnite/Auth.php(48)

Fortnite\FortniteClient::sendUnrealClientPostRequest('https://account...', Array) #1 /home/xxxxxx/api/xxxxxx/index.php(7): 

Fortnite\Auth::login('xxxxxx@xxxxxx', 'xxxxxx')

 #2 {main} thrown in /home/xxxxxx/api/xxxxxx/libs/Fortnite/FortniteClient.php on line 67

```

code 
```
<?php

require_once 'libs/Fortnite/auto_loader.php';

use Fortnite\Auth;

$auth = Auth::login('xxx','xxx);
var_dump($auth->profile->stats);

?>
```

in auto_loader.php

```
require_once('Exception/InvalidGameModeException.php');
require_once('Exception/InvalidStatException.php');
require_once('Exception/StatsNotFoundException.php');
require_once('Exception/UserNotFoundException.php');
require_once('Model/FortniteStats.php');
require_once('Model/Items.php');
require_once('Auth.php');
require_once('Stats.php');
require_once('Platform.php');
require_once('Profile.php');
require_once('FortniteClient.php');
```

If you know how to solve my problem, in any case very pretty work 😄

**Comment by Tustin** [comment]
Looks like you don't have Guzzle installed. If you just pulled in the project from this repo, you should delete it and run this command `composer require tustin/fortnite-php`. That will install the project to whatever directory you ran the command in, along with install all the dependencies (Guzzle included).

If you just want to pull in the project from this repo, you'll have to run `composer update` in the project directory to install the dependencies. 

If you don't have composer installed, you can download it here: https://getcomposer.org/

**Comment by ginoname** [comment]
Got same issue with installed Guzzle.

1281#0: *28225541 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://account-public-service-prod03.ol.epicgames.com/account/api/oauth/token` resulted in a `400 Bad Request` response:
{
"errorCode" : "errors.com.epicgames.account.invalid_account_credentials",
"errorMessage" : "Sorry the account cred (truncated...)
in /domain/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /domain/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /domain/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /domain/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\P" while reading response header from upstream
