### ISSUE TITLE
Specific Season stats

### ISSUE THREAD

**Issue by NeVeR2TrY** [Tustin/fortnite-php#30]
Cant i get the stats for a specific season, not alltime?

i tried to change in stats.php from bulk/window/alltime to season4 or season5 it doesn't work :/ 

how fortnitetracker and fortnite api gets the stats of each season ?

**Comment by Tustin** [comment]
I don't know if that data actually exists in the API but it's possible that those sites save the stats after a certain season in their own database and then just subtract those old stats from the current stats to get the current season stats. Again, this is all just speculation and I haven't actually tried to see if you can get that data automatically.

**Comment by atgrau** [comment]
Maybe, they store data when season finalize.

**Comment by NeVeR2TrY** [comment]
how to store the data for 3 million users 😮

**Comment by NeVeR2TrY** [comment]
@Tustin you must find a way to get data for each season 😃 i believe that epic games stores it, since it stores account level in profile 👍 the level is the summation of all seasons levels

**Comment by KilianSmt** [comment]
EG store a bunch of information (even the names of the players you have to kill for example) but they are for support. The current trackers do it manually (even fortnitetracker), for my part I make a table where I add a line when a new season comes and when the profile is updated I compare the stats overall received by the API and those of my site then I add the difference in another table that looks like something like this: id / season / eg account token / array of stats

**Comment by Tustin** [comment]
Thanks @KilianSmt. I looked at nearly every endpoint I could when I originally reversed the API but never came across specific season stats so I just assumed that's how all the sites worked 😄.

**Comment by NeVeR2TrY** [comment]
@Tustin you can change window instead of alltime to weekly to get season5 statistics
