### ISSUE TITLE
Can't Seem to fetch news : Undefined class constant 'BATTLEROYALE'

### ISSUE THREAD

**Issue by dpather** [Tustin/fortnite-php#37]
Hi, I am getting this error when trying to retrieve the BattleRoyale news:

PHP Fatal error:  Uncaught Error: Undefined class constant 'BATTLEROYALE'

Solved:

Used **NewsType**::'BATTLEROYALE'

instead of **News**::'BATTLEROYALE'

**Comment by Tustin** [comment]
If you're using the most recent version, it should be News::BATTLEROYALE. I made that change a few weeks ago.
