### ISSUE TITLE
Specific Player Stats Error

### ISSUE THREAD

**Issue by NeVeR2TrY** [Tustin/fortnite-php#43]
Hello, a user using my website reported for an issue with his account, i tried to get data using his name and his id but i get this error "Invalid argument supplied for foreach()", 
He is a ps4 user and changed his name on epic and ps4 newly after the change he started getting this error.

**Comment by RobertoGraham** [comment]
What are his username and id?

**Comment by NeVeR2TrY** [comment]
@RobertoGraham
MinMindz
f4d6469f8d0c43519e9c8726e93a0a27

**Comment by monkeydioude** [comment]
Doesn't seem to exist, I get 404 in my API with his ID on all platforms

**Comment by atgrau** [comment]
I think this player does not play any match in any platform yet...

![screenshot](https://user-images.githubusercontent.com/18336235/44791950-23984200-aba3-11e8-8c62-d7ec43caea25.PNG)

**Comment by NeVeR2TrY** [comment]
https://fortnitetracker.com/profile/psn/MinMindz

**Comment by RobertoGraham** [comment]
I am seeing many instances of this in my own app. For these IDs an account exists but when I fetch statistics for them I get a 204 No Content response. If it happened after he changed his name I guess it's because he has no matches under his new name or something
![screen shot 2018-08-29 at 14 53 05](https://user-images.githubusercontent.com/14958777/44792120-17a88200-ab9b-11e8-980e-e64c829d3b1d.png)

**Comment by NeVeR2TrY** [comment]
He said that he played some games in the new name ..

**Comment by RobertoGraham** [comment]
Can you ask him if he sees his kill count going up on the career tab in-game or they are frozen?

**Comment by NeVeR2TrY** [comment]
![40307913_410672352791687_673799309824622592_n](https://user-images.githubusercontent.com/20230555/44792909-a3c3a500-abad-11e8-8c0a-bac15e0ea123.jpg)
Heres the data

**Comment by monkeydioude** [comment]
Glad to see that Time Player stat is messed even for their own client :o)

**Comment by RobertoGraham** [comment]
Super weird... Maybe there is a new stats endpoint

**Comment by NeVeR2TrY** [comment]
@RobertoGraham other players has no problem, i get stats normally
even this username data are retrieved normally from https://fortnitetracker.com/profile/psn/MinMindz

**Comment by atgrau** [comment]
Apps like fortnitetracker, store player's information in their own database, so if the user CHANGE his name, they still have this information, in this API, we fetch actual player stats, so if the user has been changed his name, information won't be shown anymore...

**Comment by atgrau** [comment]
I think its for this reason: 

> Apps like fortnitetracker, store player's information in their own database, ... 

Maybe, firstly his privacy was public...

**Comment by NeVeR2TrY** [comment]
@atgrau  even though his stats was keep updating while its private 😮

**Comment by atgrau** [comment]
@NeVeR2TrY Sure about that? If so, then they're using another endpoint...

Furthermore, how it's possible they store player stats splitted in seasons?

**Comment by NeVeR2TrY** [comment]
@atgrau rather than the stats in each season how they get the leaderboard of kills,score, etc ... while this endpoint just return a wins only..

**Comment by monkeydioude** [comment]
@NeVeR2TrY there's an endpoint for leaderboards iirc

Other than that, there's always the option of massive storing of stats and making a leaderboard out of it

**Comment by NeVeR2TrY** [comment]
@monkeydioude  so i can get the leaderboard of kills using the endpoint?

**Comment by RobertoGraham** [comment]
@NeVeR2TrY Just for wins as far as I can tell, though I have not tried every combo of platform, party size, time window, stat type

**Comment by NeVeR2TrY** [comment]
@RobertoGraham i have tried some none worked, changing global to group and place_top_1 to place_top_3 gives some random players idk from where they come
