### ISSUE TITLE
API is no longer usable

### ISSUE THREAD

**Issue by Krokit** [Tustin/fortnite-php#5]
Hello, I just install package and configure it but now I can see API is no longer accessible. 

Client error: `POST https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/game/v2/profile/10722fbb55c5414a9d5acc1427a838e5/client/QueryProfile?pr ▶
{"errorCode":"errors.com.epicgames.common.missing_action","errorMessage":"Login is banned or does not posses the action  

I update User-Agent parameters to the latest version of the launcher and no success.

**Comment by Krokit** [comment]
I find where was the problem if the developer creates a new account like me for API only he will need to login to fortnite and play 1 game. :)

**Comment by Tustin** [comment]
Yep, I noticed that when I was working on this but I failed to mention it anywhere. I'll add a warning to the readme stating that you need to use an account that has played Fortnite before! :)
