### ISSUE TITLE
unauthorized_client

### ISSUE THREAD

**Issue by kavvson** [Tustin/fortnite-php#56]
{#448 ▼
  +"errorCode": "errors.com.epicgames.common.oauth.unauthorized_client"
  +"errorMessage": "Sorry your client is not allowed to use the grant type password"
  +"messageVars": []
  +"numericErrorCode": 1015
  +"originatingService": "com.epicgames.account.public"
  +"intent": "prod"
  +"error_description": "Sorry your client is not allowed to use the grant type password"
  +"error": "unauthorized_client"
}

Did they change anything recently? It was working yesterday

**Comment by xSevithx** [comment]
Same thing here. API has stopped working earlier. I have tried and my accounts are not locked but it looks like something was changed with the recent update perhaps?

**Comment by xSevithx** [comment]
https://github.com/SzymonLisowiec/node-epicgames-client/issues/15#issuecomment-446396100

**Comment by atgrau** [comment]
Same.

**Comment by Tustin** [comment]
Let me know if that fixes the problem for you. The solution in the issue linked above seems a bit more convoluted than what's necessary. All I had to do was update the Authorization header and it started working again.

**Comment by xSevithx** [comment]
Fixed and works for me.
