### ISSUE TITLE
Uncaught Error: Class 'Language' not found

### ISSUE THREAD

**Issue by ginoname** [Tustin/fortnite-php#6]
Hello I have some problems with latest version. 
Get leadeboards is not working because:
`Uncaught Error: Class 'Platform' not found`
news and store not working because
`Uncaught Error: Class 'Language' not found`
Full error:
```
FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Class 'Language' not found in /domain/file.php:5
Stack trace:
#0 {main}
thrown in /domain/file.php on line 5" while reading response header from upstream
```

My code:
```
<?php
require_once 'vendor/autoload.php';
use Fortnite\Auth;
$auth = Auth::login('x@x.x','x');
var_dump($auth->store->getStore(Language::ENGLISH));
```

**Comment by Fyris** [comment]
`<?php
require_once 'vendor/autoload.php';
use Fortnite\Auth;
use Fortnite\Platform;
use Fortnite\Language;
$auth = Auth::login('x@x.x','x');
var_dump($auth->store->getStore(Language::ENGLISH));`

Should work by adding "use Fortnite\Platform" or "use Fortnite\Language". 
Also this repo does not have the modifications you're using so i suggest adding any further issues you have to the fork which does.
