### ISSUE TITLE
Problem with Stats.php

### ISSUE THREAD

**Issue by AlbyMangels** [Tustin/fortnite-php#7]
PHP Parse error:  syntax error, unexpected 'array' (T_ARRAY), expecting ';' or '{' in /var/www/fortniteleaderboards.org/vendor/tustin/fortnite-php/src/Stats.php on line 98

**Comment by Tustin** [comment]
Update PHP to 7.0. I use type declarations in this library to specify return type values. I'll add the minimum PHP version required to composer.json so this problem shouldn't pop up again.
