### ISSUE TITLE
problem with fortniteleaderboardData

### ISSUE THREAD

**Issue by AlbyMangels** [Tustin/fortnite-php#8]
I am now using php 7 but am getting this error? Any ideas?

PHP Warning:  Division by zero in /var/www/fortnitetest/vendor/tustin/fortnite-php/src/Model/FortniteStats.php on line 72
PHP Fatal error:  Uncaught Error: Call to undefined method Fortnite\Leaderboard::getLeaderboardData() in /var/www/fortnitetest/basic2.php:18
Stack trace:
#0 {main}
  thrown in /var/www/fortnitetest/basic2.php on line 18

**Comment by Tustin** [comment]
@Fyris looks like a problem with the code you added. You're trying to calculate the custom properties (kill/death, win/loss, etc) without doing a check to make sure the divisor in each statement isn't zero. This would be an issue for people who haven't played the game but want to use this library for stat lookup or something. I'll add the checks and commit the change.

**Comment by AlbyMangels** [comment]
I was using the example leaderboard code that came in the distribution

**Comment by AlbyMangels** [comment]
oh ok thanks

**Comment by Tustin** [comment]
Oh my bad! I like to use the shorthand names like that because some of the previous ones just seem redundant. Although I am surprised that PHP only throws a warning on a division by zero error.

**Comment by AlbyMangels** [comment]
Thanks Fyris and my bad I probably should have dug a bit deeper.
